language: python
python:
  - "2.7"
install:
  - pip install --upgrade pip
before_script:
  - pip install -r requirements.txt
script:
  - coverage run --source=app manage.py test
after_success:
  - coveralls --ignore-errors