language: python
python:
  - "2.7"
install:
  - pip install -U pip
before_script:
  - pip install -r requirements.txt --use-mirrors
script:
  - coverage run --source=app manage.py test
after_success:
  - coveralls --ignore-errors