language: python
python:
  - "2.7"
install:
  - pip install --upgrade pip
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - rackup  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc
  - pip install -r requirements.txt
  - pip install python-coveralls
script:
  - coverage run --source=app manage.py test
after_success:
  - coveralls --ignore-errors
