language: python
python:
  - "2.7"
install:
  - pip install --upgrade pip
before_script:
  - "export GOCEPT_SELENIUM_BROWSER='*firefox'"
  - pip install -r requirements.txt
  - pip install python-coveralls
script:
  - coverage run --source=app manage.py test
after_success:
  - coveralls --ignore-errors
